/*BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE EDUCATION CASCADE CONSTRAINTS';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE CAREER CASCADE CONSTRAINTS';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE CERTIFICATE CASCADE CONSTRAINTS';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE RECRUIT CASCADE CONSTRAINTS';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE LOCATION CASCADE CONSTRAINTS';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EDUCATION';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CAREER';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CERTIFICATE';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RECRUIT';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOCATION';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
END;
 */

DROP TABLE IF EXISTS EDUCATION;
DROP TABLE IF EXISTS CAREER;
DROP TABLE IF EXISTS CERTIFICATE;
DROP TABLE IF EXISTS RECRUIT;
DROP TABLE IF EXISTS LOCATION;

DROP SEQUENCE IF EXISTS SEQ_EDUCATION;
DROP SEQUENCE IF EXISTS SEQ_CAREER;
DROP SEQUENCE IF EXISTS SEQ_CERTIFICATE;
DROP SEQUENCE IF EXISTS SEQ_RECRUIT;
DROP SEQUENCE IF EXISTS SEQ_LOCATION;