DROP TABLE IF EXISTS EDUCATION;
DROP TABLE IF EXISTS CAREER;
DROP TABLE IF EXISTS CERTIFICATE;
DROP TABLE IF EXISTS RECRUIT;
DROP TABLE IF EXISTS LOCATION;

DROP SEQUENCE IF EXISTS SEQ_EDUCATION;
DROP SEQUENCE IF EXISTS SEQ_CAREER;
DROP SEQUENCE IF EXISTS SEQ_CERTIFICATE;
DROP SEQUENCE IF EXISTS SEQ_RECRUIT;
DROP SEQUENCE IF EXISTS SEQ_LOCATION;


CREATE TABLE LOCATION
(
    LOC_SEQ  NUMBER(19, 0) NOT NULL,
    LOC_NAME VARCHAR2(10)  NOT NULL
);

CREATE TABLE RECRUIT
(
    REC_SEQ       NUMBER(19, 0)           NOT NULL,
    NAME          VARCHAR2(255)           NOT NULL,
    PASSWORD_HASH VARCHAR2(255)           NOT NULL,
    BIRTH         DATE                    NULL,
    GENDER        VARCHAR2(10)            NULL,
    PHONE         VARCHAR2(15)            NOT NULL,
    EMAIL         VARCHAR2(255)           NULL,
    ADDRESS       CLOB                    NULL,
    LOC_SEQ       NUMBER(19)              NULL,
    WORK_TYPE     VARCHAR2(10)            NULL,
    SUBMIT        VARCHAR2(1) DEFAULT 'N' NOT NULL
);

CREATE TABLE EDUCATION
(
    EDU_SEQ      NUMBER(19, 0) NOT NULL,
    REC_SEQ      NUMBER(19, 0) NOT NULL,
    SCHOOL_NAME  VARCHAR2(255) NOT NULL,
    SCHOOL_TYPE  VARCHAR2(255) NOT NULL,
    DIVISION     VARCHAR2(255) NOT NULL,
    START_PERIOD DATE          NOT NULL,
    END_PERIOD   DATE          NOT NULL,
    MAJOR        VARCHAR2(255) NOT NULL,
    GRADE        NUMBER(10, 2) NOT NULL,
    LOC_SEQ      NUMBER(19, 0) NOT NULL
);

CREATE TABLE CAREER
(
    CAR_SEQ      NUMBER(19, 0) NOT NULL,
    REC_SEQ      NUMBER(19, 0) NOT NULL,
    COMP_NAME    VARCHAR2(255) NOT NULL,
    LOC_SEQ      NUMBER(19, 0) NOT NULL,
    START_PERIOD DATE          NOT NULL,
    END_PERIOD   DATE          NOT NULL,
    TASK         VARCHAR2(255) NOT NULL
);

CREATE TABLE CERTIFICATE
(
    CERT_SEQ      NUMBER(19, 0) NOT NULL,
    REC_SEQ       NUMBER(19, 0) NOT NULL,
    QUALIFY_NAME  VARCHAR2(255) NOT NULL,
    ACQU_DATE     DATE          NOT NULL,
    ORGANIZE_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_LOCATION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_RECRUIT
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_EDUCATION
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_CAREER
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_CERTIFICATE
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

ALTER TABLE LOCATION
    ADD CONSTRAINT PK_LOCATION PRIMARY KEY (LOC_SEQ);

ALTER TABLE LOCATION
    ADD CONSTRAINT UQ_LOCATION_LOC_NAME UNIQUE (LOC_NAME);

ALTER TABLE RECRUIT
    ADD CONSTRAINT PK_RECRUIT PRIMARY KEY (REC_SEQ);

ALTER TABLE RECRUIT
    ADD CONSTRAINT FK_LOCATION_TO_RECRUIT_1 FOREIGN KEY (LOC_SEQ) REFERENCES LOCATION (LOC_SEQ);

ALTER TABLE RECRUIT
    ADD CONSTRAINT UQ_RECRUIT_NAME_AND_PHONE UNIQUE (NAME, PHONE);

ALTER TABLE RECRUIT
    ADD CONSTRAINT CHK_RECRUIT_GENDER CHECK (GENDER IN ('M', 'F'));

ALTER TABLE RECRUIT
    ADD CONSTRAINT CHK_RECRUIT_WORK_TYPE CHECK (WORK_TYPE IN ('FULL_TIME', 'NON_REGULAR'));

ALTER TABLE EDUCATION
    ADD CONSTRAINT PK_EDUCATION PRIMARY KEY (EDU_SEQ);

ALTER TABLE EDUCATION
    ADD CONSTRAINT FK_RECRUIT_TO_EDUCATION_1 FOREIGN KEY (REC_SEQ) REFERENCES RECRUIT (REC_SEQ);

ALTER TABLE EDUCATION
    ADD CONSTRAINT FK_LOCATION_TO_EDUCATION_1 FOREIGN KEY (LOC_SEQ) REFERENCES LOCATION (LOC_SEQ);

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_PERIOD CHECK (START_PERIOD <= END_PERIOD);

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_SCHOOL_TYPE CHECK (SCHOOL_TYPE IN ('HIGH_SCHOOL', 'ASSOCIATE
', 'BACHELOR', 'MASTER', 'DOCTORATE'));

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_DIVISION
        CHECK ( DIVISION IN ('GRADUATED', 'ENROLLED', 'DROPPED_OUT'));

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_GRADE CHECK (GRADE <= 4.50);

ALTER TABLE CAREER
    ADD CONSTRAINT PK_CAREER PRIMARY KEY (CAR_SEQ);

ALTER TABLE CAREER
    ADD CONSTRAINT FK_RECRUIT_TO_CAREER_1 FOREIGN KEY (REC_SEQ) REFERENCES RECRUIT (REC_SEQ);

ALTER TABLE CAREER
    ADD CONSTRAINT FK_LOCATION_TO_CAREER_1 FOREIGN KEY (LOC_SEQ) REFERENCES LOCATION (LOC_SEQ);

ALTER TABLE CAREER
    ADD CONSTRAINT CHK_CAREER_PERIOD CHECK (START_PERIOD <= END_PERIOD);

ALTER TABLE CERTIFICATE
    ADD CONSTRAINT PK_CERTIFICATE PRIMARY KEY (CERT_SEQ);

ALTER TABLE CERTIFICATE
    ADD CONSTRAINT FK_RECRUIT_TO_CERTIFICATE_1 FOREIGN KEY (REC_SEQ) REFERENCES RECRUIT (REC_SEQ);

CREATE INDEX IX_EDUCATION_REC_SEQ ON EDUCATION (REC_SEQ);

CREATE INDEX IX_CAREER_REC_SEQ ON CAREER (REC_SEQ);

CREATE INDEX IX_CERTIFICATE_REC_SEQ ON CERTIFICATE (REC_SEQ);

CREATE INDEX IX_RECRUIT_LOC_SEQ ON RECRUIT (LOC_SEQ);

CREATE INDEX IX_EDUCATION_LOC_SEQ ON EDUCATION (LOC_SEQ);

CREATE INDEX IX_CAREER_LOC_SEQ ON CAREER (LOC_SEQ);

INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '서울');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '부산');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '대구');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '인천');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '광주');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '대전');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '울산');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '세종');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '경기');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '충북');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '충남');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '전북');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '전남');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '경북');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '경남');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '제주');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '강원');