CREATE TABLE RECRUIT
(
    REC_SEQ       NUMBER(19, 0) NOT NULL,
    NAME          VARCHAR2(255) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    BIRTH     DATE NULL,
    GENDER        VARCHAR2(10) NULL,
    PHONE         VARCHAR2(15) NOT NULL,
    EMAIL         VARCHAR2(255) NULL,
    ADDRESS       CLOB NULL,
    LOCATION      VARCHAR2(10) NULL,
    WORK_TYPE     VARCHAR2(10) NULL,
    SUBMIT        VARCHAR2(1) DEFAULT 'N' NOT NULL
);

CREATE TABLE EDUCATION
(
    EDU_SEQ      NUMBER(19, 0)		NOT NULL,
    REC_SEQ      NUMBER(19, 0)		NOT NULL,
    SCHOOL_NAME  VARCHAR2(255)		NOT NULL,
    SCHOOL_TYPE  VARCHAR2(255)		NOT NULL,
    DIVISION     VARCHAR2(255)		NOT NULL,
    START_PERIOD DATE NOT NULL,
    END_PERIOD   DATE NOT NULL,
    MAJOR        VARCHAR2(255)		NOT NULL,
    GRADE        NUMBER(10, 2)		NOT NULL,
    LOCATION     VARCHAR2(10)	NOT NULL
);

CREATE TABLE CAREER
(
    CAR_SEQ      NUMBER(19, 0) NOT NULL,
    REC_SEQ      NUMBER(19, 0) NOT NULL,
    COMP_NAME    VARCHAR2(255) NOT NULL,
    LOCATION     VARCHAR2(10) NOT NULL,
    START_PERIOD DATE NOT NULL,
    END_PERIOD   DATE NOT NULL,
    TASK         VARCHAR2(255) NOT NULL
);

CREATE TABLE CERTIFICATE
(
    CERT_SEQ      NUMBER(19, 0) NOT NULL,
    REC_SEQ       NUMBER(19, 0) NOT NULL,
    QUALIFY_NAME  VARCHAR2(255) NOT NULL,
    ACQU_DATE     DATE NOT NULL,
    ORGANIZE_NAME VARCHAR2(255) NOT NULL
);

ALTER TABLE RECRUIT
    ADD CONSTRAINT PK_RECRUIT PRIMARY KEY (REC_SEQ);

ALTER TABLE RECRUIT
    ADD CONSTRAINT UQ_RECRUIT_NAME_AND_PHONE UNIQUE (NAME, PHONE);

ALTER TABLE RECRUIT
    ADD CONSTRAINT CHK_RECRUIT_GENDER CHECK (GENDER IN ('남자', '여자'));

ALTER TABLE RECRUIT
    ADD CONSTRAINT CHK_RECRUIT_LOCATION CHECK (LOCATION IN
                                               ('서울', '경기', '인천', '강원', '대전', '세종', '충남', '충북', '대구', '부산', '울산', '경북',
                                                '경남', '광주', '전북', '전남', '제주'));

ALTER TABLE RECRUIT
    ADD CONSTRAINT CHK_RECRUIT_WORK_TYPE CHECK (WORK_TYPE IN ('정규직', '비정규직'));

ALTER TABLE RECRUIT
    ADD CONSTRAINT CHK_RECRUIT_SUBMIT CHECK (SUBMIT IN ('Y', 'N'));

ALTER TABLE EDUCATION
    ADD CONSTRAINT PK_EDUCATION PRIMARY KEY (EDU_SEQ);

ALTER TABLE EDUCATION
    ADD CONSTRAINT FK_RECRUIT_TO_EDUCATION_1 FOREIGN KEY (REC_SEQ) REFERENCES RECRUIT (REC_SEQ);

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_PERIOD CHECK (START_PERIOD <= END_PERIOD);

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_LOCATION CHECK (LOCATION IN
                                                 ('서울', '경기', '인천', '강원', '대전', '세종', '충남', '충북', '대구', '부산', '울산',
                                                  '경북', '경남', '광주', '전북', '전남', '제주'));

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_SCHOOL_TYPE CHECK (SCHOOL_TYPE IN ('고등학교', '학사', '석사', '박사'));

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_DIVISION CHECK (DIVISION IN ('졸업', '재학', '중퇴'));

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_GRADE CHECK (GRADE <= 4.50);

ALTER TABLE CAREER
    ADD CONSTRAINT PK_CAREER PRIMARY KEY (CAR_SEQ);

ALTER TABLE CAREER
    ADD CONSTRAINT FK_RECRUIT_TO_CAREER_1 FOREIGN KEY (REC_SEQ) REFERENCES RECRUIT (REC_SEQ);

ALTER TABLE CAREER
    ADD CONSTRAINT CHK_CAREER_LOCATION CHECK (LOCATION IN
                                              ('서울', '경기', '인천', '강원', '대전', '세종', '충남', '충북', '대구', '부산', '울산', '경북',
                                               '경남', '광주', '전북', '전남', '제주'));

ALTER TABLE CAREER
    ADD CONSTRAINT CHK_CAREER_PERIOD CHECK (START_PERIOD <= END_PERIOD);

ALTER TABLE CERTIFICATE
    ADD CONSTRAINT PK_CERTIFICATE PRIMARY KEY (CERT_SEQ);

ALTER TABLE CERTIFICATE
    ADD CONSTRAINT FK_RECRUIT_TO_CERTIFICATE_1 FOREIGN KEY (REC_SEQ) REFERENCES RECRUIT (REC_SEQ);

CREATE SEQUENCE SEQ_RECRUIT
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_EDUCATION
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_CAREER
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_CERTIFICATE
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE INDEX IX_EDUCATION_REC_SEQ ON EDUCATION (REC_SEQ);

CREATE INDEX IX_CAREER_REC_SEQ ON CAREER (REC_SEQ);

CREATE INDEX IX_CERTIFICATE_REC_SEQ ON CERTIFICATE (REC_SEQ);