ALTER TABLE RECRUIT
    DROP CONSTRAINT CHK_RECRUIT_LOCATION;
ALTER TABLE EDUCATION
    DROP CONSTRAINT CHK_EDUCATION_LOCATION;
ALTER TABLE EDUCATION
    DROP CONSTRAINT CHK_EDUCATION_SCHOOL_TYPE;
ALTER TABLE EDUCATION
    DROP CONSTRAINT CHK_EDUCATION_DIVISION;
ALTER TABLE CAREER
    DROP CONSTRAINT CHK_CAREER_LOCATION;

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_SCHOOL_TYPE CHECK (SCHOOL_TYPE IN ('HIGH_SCHOOL', 'ASSOCIATE
', 'BACHELOR', 'MASTER', 'DOCTORATE'));

ALTER TABLE EDUCATION
    ADD CONSTRAINT CHK_EDUCATION_DIVISION
        CHECK ( DIVISION IN ('GRADUATED', 'ENROLLED', 'DROPPED_OUT'));

ALTER TABLE RECRUIT
    MODIFY LOCATION NUMBER(19, 0);
ALTER TABLE EDUCATION
    MODIFY LOCATION NUMBER(19, 0);
ALTER TABLE CAREER
    MODIFY LOCATION NUMBER(19, 0);

ALTER TABLE RECRUIT RENAME COLUMN LOCATION TO LOC_SEQ;
ALTER TABLE EDUCATION RENAME COLUMN LOCATION TO LOC_SEQ;
ALTER TABLE CAREER RENAME COLUMN LOCATION TO LOC_SEQ;

CREATE TABLE LOCATION
(
    LOC_SEQ  NUMBER(19, 0) NOT NULL,
    LOC_NAME VARCHAR2(10)  NOT NULL
);

CREATE SEQUENCE SEQ_LOCATION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

ALTER TABLE LOCATION
    ADD CONSTRAINT PK_LOCATION PRIMARY KEY (LOC_SEQ);
ALTER TABLE LOCATION
    ADD CONSTRAINT UQ_LOCATION_LOC_NAME UNIQUE (LOC_NAME);

INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '서울');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '부산');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '대구');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '인천');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '광주');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '대전');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '울산');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '세종');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '경기');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '충북');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '충남');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '전북');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '전남');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '경북');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '경남');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '제주');
INSERT INTO LOCATION (LOC_SEQ, LOC_NAME)
VALUES (SEQ_LOCATION.NEXTVAL, '강원');

ALTER TABLE RECRUIT
    ADD CONSTRAINT FK_LOCATION_TO_RECRUIT_1 FOREIGN KEY (LOC_SEQ) REFERENCES LOCATION (LOC_SEQ);

ALTER TABLE EDUCATION
    ADD CONSTRAINT FK_LOCATION_TO_EDUCATION_1 FOREIGN KEY (LOC_SEQ) REFERENCES LOCATION (LOC_SEQ);

ALTER TABLE CAREER
    ADD CONSTRAINT FK_LOCATION_TO_CAREER_1 FOREIGN KEY (LOC_SEQ) REFERENCES LOCATION (LOC_SEQ);