ALTER TABLE RECRUIT
    DROP CONSTRAINT CHK_RECRUIT_GENDER;

ALTER TABLE RECRUIT
    ADD CONSTRAINT CHK_RECRUIT_GENDER CHECK (GENDER IN ('M', 'F'));

ALTER TABLE RECRUIT
    DROP CONSTRAINT CHK_RECRUIT_WORK_TYPE;

ALTER TABLE RECRUIT
    ADD CONSTRAINT CHK_RECRUIT_WORK_TYPE CHECK (WORK_TYPE IN ('FULL_TIME', 'NON_REGULAR'));